### ISSUE TITLE
ci: pytest | tee swallows exit code — 38 failures masked as success (pipefail missing, FAILED not counted)

### ISSUE THREAD

**Issue by dahai80** [dahai80/fusion-mlx#583]
### Summary
`gh run list` reports **success** for every recent `main` CI run, but the actual test step log shows **38 failed, 10997 passed** (3.12 matrix job, run 32390849022, job 96496316663).

### Root cause
`.github/workflows/ci.yml` test step:
```yaml
pytest tests/unit -v --tb=short --cov=fusion_mlx ... --junitxml=pytest-junit.xml 2>&1 | tee pytest-output.txt
```
The pipe `| tee` makes the step's exit code **`tee`'s exit code (0)**, not pytest's. Pytest's non-zero exit (failures present) is swallowed.

The follow-up "guard against excessive skips" step only counts `PASSED` and `SKIPPED`:
```bash
PASSED=$(grep -cE ' PASSED \[' pytest-output.txt || echo 0)
SKIPPED=$(grep -cE ' SKIPPED \[' pytest-output.txt || echo 0)
TESTS=$((PASSED + SKIPPED))
PCT=$((SKIPPED * 100 / TESTS))
```
It **never checks FAILED**, so 38 failures + 3% skips = guard passes = job green.

### Evidence
```
= 38 failed, 10997 passed, 390 skipped, 269 xfailed, 136 xpassed, 744 warnings in 1007.15s =
Passed: 10641, Skipped: 378/11019 (3%)
```
All jobs report `success`:
```
test (3.12) success
test (3.11) success
test (3.13) success
lint success
```

### Fix
1. Preserve pytest exit code: `set -o pipefail` before the `pytest | tee` line, OR capture explicitly:
   ```bash
   set -o pipefail
   pytest ... 2>&1 | tee pytest-output.txt
   ```
2. Add FAILED to the guard so failures fail the job:
   ```bash
   FAILED=$(grep -cE ' FAILED \[' pytest-output.txt || echo 0)
   if [ "$FAILED" -gt 0 ]; then echo "FAIL: ${FAILED} tests failed"; exit 1; fi
   ```

### The 38 failures (pre-existing on main)
| file | count | error |
|------|-------|-------|
| test_embedding.py | 9 | `AttributeError: <module 'mlx_embeddings'> does not have the attribute 'generate'` — **FIXED in PR #582** (conftest guard) |
| test_pytorch_weight_loading.py | 6 | torch stub / safetensors conversion |
| test_sanitize_output.py | 5 | gemma4 sanitizer `assert out is None` got `'call:add{...}'` |
| test_server_api_key_env_fallback.py | 4 | api_key env/argv resolution |
| test_image_gen_sd15.py | 5 | SD15 img2img forwarding |
| test_image_gen_sd2.py | 3 | SD2 forwarding |
| test_gen_acceleration_knobs.py | 2 | `SimpleNamespace has no attribute 'size'` |
| test_embeddings_timeout_admission.py | 1 | XPASS(strict) — xfail marker stale |
| test_mcp_config.py | 1 | example round-trip |
| test_modality_models_route.py | 1 | EntryPayload all-fields |
| test_ui_tars_lane_parity.py | 1 | reasoning alias |

### Impact
Main branch appears green while carrying 38 failures. Regressions land undetected. The 9 embedding failures are fixed by #582; the remaining 29 need separate triage.

### Note
This is an **upstream-adjacent / CI-config** issue, filed per project workflow (issue first, then PR). I will open a PR to fix the masker (`pipefail` + FAILED guard) after this issue is triaged.
